ACCommunity/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, MultipleFileField
from wtforms.validators import DataRequired
from ACCommunity.models import BlogPostImage
from flask_wtf.file import FileField, FileAllowed


class BlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    images = MultipleFileField("Image(s) Upload", render_kw={"multiple": True})
    # images = FileField("Update Image", validators=[FileAllowed(["jpg", "jpeg", "png"])])
    submit = SubmitField("Post")

ACCommunity/blog_posts/views.py
# To-do
# 1. DONE! change the redirect of create post view and delete post view to post list view
# 2. add pictures to create post view (need to change db model and form)
# 3. DONE! Add titles to templates
# 4. DONE! add profile image next to each post
# 5. DONE! make usernames in posts clickable
import os
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import current_user, login_required
from ACCommunity import db
from ACCommunity.models import BlogPost, BlogPostImage
from ACCommunity.blog_posts.forms import BlogPostForm
from ACCommunity.blog_posts.picture_handler import add_post_pic

blog_posts = Blueprint("blog_posts", __name__)


# create post
@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()

        if form.images.data:
            counter = 0
            for image in form.images.data:
                if image.filename:
                    counter += 1
                    post_id = blog_post.id
                    pic = add_post_pic(image, post_id, counter)
                    new_pic = BlogPostImage(pic, post_id)
                    db.session.add(new_pic)
                    db.session.commit()

        flash("Post created!")
        return redirect(url_for("blog_posts.all_posts"))

    return render_template("create_post.html", form=form, page_title="CREATE POST", show_image=True)


# view single post
@blog_posts.route("/<int:blog_post_id>")
def blog_post(blog_post_id):
    blog_post_found = BlogPost.query.get_or_404(blog_post_id)
    images_found = BlogPostImage.query.filter_by(post_id=blog_post_id)
    print(type(images_found))
    return render_template("blog_post.html", post=blog_post_found, images=images_found, page_title=blog_post_found.title.upper())


# update post
@blog_posts.route("/<int:blog_post_id>/update", methods=["GET", "POST"])
@login_required
def update(blog_post_id):
    blog_post_found = BlogPost.query.get_or_404(blog_post_id)
    if blog_post_found.author != current_user:
        abort(403)

    form = BlogPostForm()

    show_image = False if BlogPostImage.query.filter_by(post_id=blog_post_id).first() else True

    if form.validate_on_submit():

        if form.images.data:
            counter = 0
            for image in form.images.data:
                counter += 1
                post_id = blog_post_found.id
                pic = add_post_pic(image, post_id, counter)
                new_pic = BlogPostImage(pic, post_id)
                db.session.add(new_pic)
                db.session.commit()

        blog_post_found.title = form.title.data
        blog_post_found.text = form.text.data

        db.session.commit()

        flash("Post updated!")
        return redirect(url_for("blog_posts.blog_post", blog_post_id=blog_post_found.id))

    elif request.method == "GET":
        form.title.data = blog_post_found.title
        form.text.data = blog_post_found.text

    return render_template("create_post.html", form=form, show_image=show_image, page_title=blog_post_found.title.upper())


# delete post
@blog_posts.route("/<int:blog_post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(blog_post_id):
    blog_post_found = BlogPost.query.get_or_404(blog_post_id)
    if blog_post_found.author != current_user:
        abort(403)

    images_found = BlogPostImage.query.filter_by(post_id=blog_post_id)
    basedir = os.path.abspath(os.getcwd())
    image_dir = os.path.join(basedir, "ACCommunity/static/blog_post_pics")
    for image in images_found:
        os.remove(os.path.join(image_dir, image.post_image))
        db.session.delete(image)
        db.session.commit()

    db.session.delete(blog_post_found)
    db.session.commit()

    flash("Post Deleted!")

    return redirect(url_for("blog_posts.all_posts"))


# view all posts
@blog_posts.route("/all")
def all_posts():
    page = request.args.get("page", 1, type=int)
    all_posts_found = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template("all_posts.html", all_posts=all_posts_found, page_title="ALL POSTS")

ACCommunity/core/views.py
# for home view and info  view
from flask import render_template, request, Blueprint

core = Blueprint("core", __name__)


@core.route("/")
def index():
    return render_template("index.html", page_title="HOME")


@core.route("/about")
def about():
    return render_template("about.html", page_title="ABOUT")

ACCommunity/turnips/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from ACCommunity import db
from ACCommunity.models import TurnipPost
from ACCommunity.turnips.forms import TurnipPostForm

turnip_posts = Blueprint("turnip_posts", __name__)


# create turnip post
@turnip_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = TurnipPostForm()

    if form.validate_on_submit():

        turnip_post = TurnipPost(text=form.text.data,
                                 turnip_price=form.turnip_price.data,
                                 island_code=form.island_code.data,
                                 island_name=form.island_name.data,
                                 user_id=current_user.id)

        db.session.add(turnip_post)
        db.session.commit()

        flash("Turnip Post Created!")
        return redirect(url_for("turnip_posts.all_posts"))

    return render_template("create_turnip_post.html", form=form, page_title="CREATE POST")


# view single post
@turnip_posts.route("/<int:turnip_post_id>")
def turnip_post(turnip_post_id):
    turnip_post_found = TurnipPost.query.get_or_404(turnip_post_id)
    return render_template("turnip_post.html", post=turnip_post_found, page_title="ISLAND-"+turnip_post_found.island_name)


# update post
@turnip_posts.route("/<int:turnip_post_id>/update", methods=["GET", "POST"])
@login_required
def update(turnip_post_id):
    turnip_post_found = TurnipPost.query.get_or_404(turnip_post_id)
    if turnip_post_found.host != current_user:
        abort(403)

    form = TurnipPostForm()

    if form.validate_on_submit():
        turnip_post_found.text = form.text.data
        turnip_post_found.turnip_price = form.turnip_price.data
        turnip_post_found.island_code = form.island_code.data
        turnip_post_found.island_name = form.island_name.data

        db.session.commit()

        flash("Turnip Post Updated!")
        return redirect(url_for("turnip_posts.turnip_post", turnip_post_id=turnip_post_found.id))

    elif request.method == "GET":
        form.text.data = turnip_post_found.text
        form.turnip_price.data = turnip_post_found.turnip_price
        form.island_code.data = turnip_post_found.island_code
        form.island_name.data = turnip_post_found.island_name

    return render_template("create_turnip_post.html", form=form, page_title="UPDATE")


# delete post
@turnip_posts.route("/<int:turnip_post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(turnip_post_id):
    turnip_post_found = TurnipPost.query.get_or_404(turnip_post_id)
    if turnip_post_found.host != current_user:
        abort(403)

    db.session.delete(turnip_post_found)
    db.session.commit()

    flash("Post Deleted!")

    return redirect(url_for("turnip_posts.all_posts"))


# view all posts
@turnip_posts.route("/all")
def all_posts():
    page = request.args.get("page", 1, type=int)
    all_posts_found = TurnipPost.query.order_by(TurnipPost.date.desc()).paginate(page=page, per_page=5)
    return render_template("all_turnip_posts.html", all_posts=all_posts_found, page_title="ALL POSTS")

ACCommunity/users/views.py
# To-do
# 1. add bootstrap styles to register.html
# 2. add profile image to posts
# 3. implement queue function for showing island codes
# DONE! 4. create link for showing turnip posts
# 5. make all the html templates which direct to users.user_posts to a separate user page that shows both kinds of posts
# 6. DONE! fix the update-image issue
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from ACCommunity import db
from ACCommunity.models import User, BlogPost, TurnipPost
from ACCommunity.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from ACCommunity.users.picture_handler import add_profile_pic

users = Blueprint("users", __name__)


# register
@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()

        flash("Thanks for your registration!")
        return redirect(url_for("users.login"))

    return render_template("register.html", form=form, page_title="REGISTER")


# login
@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash("Log in successfully!")

            next_page = request.args.get("next")

            if next_page is None or not next_page[0] == "/":
                next_page = url_for("core.index")

            return redirect(next_page)

    return render_template("login.html", form=form, page_title="LOGIN")


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account
@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data

        db.session.commit()

        flash("User information updated!")
        return redirect(url_for("users.account"))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename="profile_pics/"+current_user.profile_image)

    return render_template("account.html", profile_image=profile_image, form=form, page_title="ACCOUNT")


# list of blog posts
@users.route("/blog/<username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template("user_blog_posts.html", blog_posts=blog_posts, user=user, page_title=user.username.upper())


# list of turnip posts
@users.route("/turnip/<username>")
def user_turnip_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    turnip_posts = TurnipPost.query.filter_by(host=user).order_by(TurnipPost.date.desc()).paginate(page=page, per_page=5)
    return render_template("user_turnip_posts.html", turnip_posts=turnip_posts, user=user, page_title=user.username.upper())

ACCommunity/templates/account.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
    <div align="center">
        <h1>Welcome to the page for {{ current_user.username }}</h1>
        <!-- <img align="center" src="{{ url_for('static', filename='profile_pics/'+current_user.profile_image) }}"> -->
        <img align="center" src="{{ profile_image }}">
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label(class='form-group') }}
            {{ form.username(class='form-control') }}
        </div>
        <div class="form-group">
            {{ form.email.label(class='form-group') }}
            {{ form.email(class='form-control') }}
        </div>
        <div class="form-group">
            {{ form.picture.label(class='form-group') }}
            {{ form.picture(class='form-control') }}
        </div>
        <div class="form-group">
            {{ form.submit(class='btn btn-primary') }}
        </div>

    </form>
</div>

{% endblock content %}

ACCommunity/templates/add_villager.html
{% extends 'base.html' %}

{% block content %}

<!-- <form method="POST">
    {{form.hidden_tag()}}
    {{form.name.label}} {{form.name}} <br>
    {{form.personality.label}} {{form.personality}} <br>
    {{form.species.label}} {{form.species}} <br>
    {{form.birthday.label}} {{form.birthday}} <br>
    {{form.submit()}}
</form> -->

<form method="POST">
    {{form.hidden_tag()}}
    <div class="form-row">
        <div class="form-group col-md-6">
            {{form.name.label(for="inputName4")}}
            {{form.name(type="text", class="form-control", id="inputName4")}}
        </div>
        <div class="form-group col-md-6">
            {{form.personality.label(for="inputPersonality4")}}
            {{form.personality(type="text", class="form-control", id="inputPersonality4")}}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            {{form.species.label(for="inputSpecies4")}}
            {{form.species(type="text", class="form-control", id="inputSpecies4")}}
        </div>
        <div class="form-group col-md-6">
            {{form.birthday.label(for="inputBirthday5")}}
            {{form.birthday(type="text", class="form-control", id="inputBirthday5")}}
        </div>
    </div>
    {{form.submit(type="submit", class="btn btn-primary")}}
</form>

{% endblock content %}

ACCommunity/templates/all_posts.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <a class="btn btn-primary" href="{{url_for('blog_posts.create_post')}}" role="button">Create Post</a>
</div>

<div class="container">
    {% for post in all_posts.items %}
    <div class="card">
        <div class="card-body">
            <h2><a class="card-title"
                    href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
            <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By:
                {{ post.author.username }}</a>
            <p>Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
            <a class="btn btn-primary" href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">Read Post</a>
            <br>
        </div>
    </div>
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in all_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if all_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('blog_posts.all_posts', page=page_num) }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog_posts.all_posts', page=page_num) }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>


{% endblock content %}

ACCommunity/templates/all_turnip_posts.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <a class="btn btn-primary" href="{{url_for('turnip_posts.create_post')}}" role="button">Create Post</a>
</div>

<div class="container">
    {% for post in all_posts.items %}
    <div class="card">
        <div class="card-body">
            <h2><a class="card-title" href="{{ url_for('turnip_posts.turnip_post', turnip_post_id=post.id) }}">Island:
                    {{ post.island_name }}</a></h2>
            <a href="{{ url_for('users.user_posts', username=post.host.username) }}">Island Owner:
                {{ post.host.username }}</a>
            <p>Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
            <p>Price on Island: {{post.turnip_price}}</p>
            <a class="btn btn-primary" href="{{ url_for('turnip_posts.turnip_post', turnip_post_id=post.id) }}">Read
                Post</a>
            <br>
        </div>
    </div>
    {% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in all_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if all_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('turnip_posts.all_posts', page=page_num) }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('turnip_posts.all_posts', page=page_num) }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>


{% endblock content %}

ACCommunity/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <title>{{page_title}}</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url_for('core.index')}}">
            <img src="{{url_for('static', filename='site_pics/home.png')}}" width="30" height="30" class="d-inline-block align-top"
                loading="lazy">
            Home
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('core.about')}}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('blog_posts.all_posts')}}">Blogs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('villagers.all_villagers')}}">Villagers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('turnip_posts.all_posts')}}">Turnips</a>
                </li>

                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.logout')}}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.login')}}">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                </li>
                    
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}
            
        {% endblock content %}
    </div>
</body>

</html>

ACCommunity/templates/blog_post.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
    <div class="media">
        <a href="{{url_for('users.user_posts', username=post.author.username)}}">
            <img src="{{ url_for('static', filename='profile_pics/'+post.author.profile_image) }}" class="mr-3" alt="">
        </a>
        <div class="media-body">
            <h5 class="mt-0">{{ post.title }}</h5>
            <h6 class="mt-0">Written by: <a
                    href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
            </h6>
            <h6>Published: {{ post.date.strftime('%B %d, %Y') }}</h6>
            <p> {{ post.text }}</p>
        </div>
    </div>
    <br>
    <div class="row row-cols-1 row-cols-md-3">
        {% for image in images %}
        <div class="col mb-4">
            <div class="card">
                <img src="{{ url_for('static', filename='blog_post_pics/'+image.post_image) }}" alt="">
            </div>
        </div>
        {% endfor %}
    </div>

    <br>

    {% if post.author == current_user %}

    <div>
        <a class="btn btn-primary" role="button"
            href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
        <br>
        <br>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
    </div>

    {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the post?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" id="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ACCommunity/templates/create_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <form class="form-group" method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class="form-control-label")}}
            {{ form.title(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.text.label(class="form-control-label")}}
            {{ form.text(class="form-control form-control-lg") }}
        </div>
        {% if show_image %}
        <div class="form-group">
            {{ form.images.label(class="form-control-label")}}
            {{ form.images(class="form-control form-control-lg") }}
        </div>
        {% endif %}
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock content %}

ACCommunity/templates/create_turnip_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <form class="form-group" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.island_name.label(class="form-control-label")}}
            {{ form.island_name(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.turnip_price.label(class="form-control-label")}}
            {{ form.turnip_price(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.island_code.label(class="form-control-label")}}
            {{ form.island_code(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.text.label(class="form-control-label")}}
            {{ form.text(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock content %}

ACCommunity/templates/edit_villager.html
{% extends 'base.html' %}
{% block content %}

{% with messages = get_flashed_messages(category_filter=["error"]) %}
{% if messages %}
<ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}
{% endwith %}

<div class="jumbotron">
    <div align="center">
        <h1>Fill out the form below to edit {{villager.name}}'s information</h1>
        <img align="center" src="{{ url_for('static', filename='villager_pics/'+villager.image) }}">
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.name.label(class='form-group')}}
            {{form.name(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.personality.label(class='form-group')}}
            {{form.personality(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.species.label(class='form-group')}}
            {{form.species(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.birthday.label(class='form-group')}}
            {{form.birthday(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.picture.label(class='form-group')}}
            {{form.picture(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
    </form>
</div>

{% endblock content %}

ACCommunity/templates/login.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
        {{form.email.label(for="exampleInputEmail1")}}
        {{form.email(type="email", class="form-control", id="exampleInputEmail1")}}
    </div>
    <div class="form-group">
        {{form.password.label(for="exampleInputPassword1")}}
        {{form.password(type="password", class="form-control", id="exampleInputPassword1")}}
    </div>
    {{form.submit(type="submit", class="btn btn-primary")}}
</form>
<br>
<h4>Don't have an account?</h4>
<a href="{{url_for('users.register')}}">
    <button type="button" class="btn btn-success">Register</button>
</a>
{% endblock content %}

ACCommunity/templates/turnip_post.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
    <div class="media">
        <a href="{{url_for('users.user_turnip_posts', username=post.host.username)}}">
            <img src="{{ url_for('static', filename='profile_pics/'+post.host.profile_image) }}" class="mr-3" alt="">
        </a>
        <div class="media-body">
            <h5 class="mt-0">Island Owner: <a href="{{url_for('users.user_posts', username=post.host.username)}}">{{ post.host.username }}</a></h5>
            <h5 class="mt-0">Island Name: {{ post.island_name }}</h5>
            <h6>Published: {{ post.date.strftime('%B %d, %Y') }}</h6>
            <h6>Price on Island: {{post.turnip_price}}</h6>
            <p> {{ post.text }}</p>
            <h6>Island Code: {{post.island_code}}</h6>
        </div>
    </div>

    <br>

    {% if post.host == current_user %}

    <div>
        <a class="btn btn-primary" role="button"
            href="{{ url_for('turnip_posts.update', turnip_post_id=post.id) }}">Update</a>
        <br>
        <br>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
    </div>

    {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the post?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                <form action="{{ url_for('turnip_posts.delete_post', turnip_post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" id="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}